[package]
name = "resin"
version = "0.1.3"
authors = ["drbawb <drbawb@fatalsyntax.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
failure = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10"
