[package]
name = "resin"
version = "0.1.5"
authors = ["drbawb <drbawb@fatalsyntax.com>"]
edition = "2018"
license = "BSD-3-Clause"

[dependencies]
byteorder = "1.3"
failure = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
