[package]
name = "resin"
version = "0.3.1"
authors = ["drbawb <drbawb@fatalsyntax.com>"]
edition = "2018"
license = "BSD-3-Clause"

[dependencies]
byteorder = "1.3"
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
